language: java

script: mvn clean compile test package

jdk:
  - oraclejdk8

env:
  global:
  - secure: YfNSXNcZacr1cYdTE/h2ue3DEU23CaRi8MRyrsFPGBKrtNDNevlOlIrTAsVT6dAHIBC66Ab6EyI8WLMm/7bcNv2xSgUC6nX7xyvpi01IwUcI7lce0PqBa07iuUkgvl8CPBWYRsble6oFdwMckgXnwcvqhE594FCf2KoLS90sl3DcV2G9DzDEKMKkbiXy8h3XTKTMVC2NlQXoyoEIqlcQgMa+erGp4cMPhgTvtmRingxTeHVCIxC0sKlfsPOFN1YffjiLJ8OdgTKSTtI6z6mXkgWDiABrQqZvYwZ1rf3s7mWn3btoKU9HTnljNTiHlRsiX4vWaJ1tWVJJySfUxfjgkuMbuJA54CZCrtWn6txfVjaZXp0BO0e9Oxq2d2PnpajlCbfKfKGMa/ji7MvWqrLvYzMQ/0BIYgX8m8Deut4x3uvLc+L8xjuphu2t3ygxNubK4b1fQPuE2qQfOLm/KrCUEeGblD03ND9gR/SrkjupVko7X4ayYU10MScvyiP5iXBzzrYc2nPotUUXp4PcYU5mfrhLcLNMakN0U3ZlPZSlis8jcPP0wNlY62HaSQLtmZbnGjDCSdwMi9ZAa5Fu3D7BRTNIaJwE77n0s6JnRQzdBulrCe+qrwjTH+ajhPFzL0bc+xL/MhHRsXML0finYoyRtw06MxAQ72ayUxXjrAz9Xl0=
  - secure: llcj9TTlIg31wLTUYLz/n2E8K3XC+izI0J44gBuOGTzf+xUv/9Oayp8CDU0/dIU0DEsNFZsXX6xjMVyDBcwmOExvGoOtc9FgtWagFJ1J4xioYFhNnie1I5rIOXXHPSN2adT/n0nMqXmgzm0srbYyxsIQUrD8MrHLOcpN/2SvvN+eZeoQHfSjpH31cAmt17s+69gdypk8m5Dd52aqT/vagsIgQHNwjNJjcniaQkKZQh0iAU/uAn40iONHl68QVDWPJPRhJwUINN7K4O3ypvlOqHou0Qa64KjbICznJJq8RWRXOTOkYo+F8OsybgHdD1UQY+cl8Qu1dFCg/cmpzlNbfgUZwMKjWT5RcK9csmXG0sPHlIycTgpbqo2GMi8f18ZWq5mXDx7+HzuNaw+9d1z8PdM+51iP0cda55lAAL2aK3DYDR5PkfiCf5bdrqhYXvJVJWy4HZHM2uS82s0pjg6ytVKItV0gefCo9ozzWthGr0JzqoxaMTe9zOz5Sp73BSlCY43n+3xTT3PoS+0WSPUCWFkMEhYU2thvKR/dZsRXS+6bZIrNLYJsv7Oz6f336q7H+sh9W3gdgJFfJEHwmLLm/uL/G6VweC9fjd2+HH3zXk/bF85XItebngkylSx3P8CkzbRYjOfy5C7Tcv+P20hFPiH6E3CJKA0D3r86xLDG4mA=

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { mvn deploy --settings settings.xml; };"
